version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2

    steps:
      - checkout

      # Download and cache dependencies

      # composer cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - run: ./vendor/bin/phpcs ./src
      - run: ./vendor/bin/phpmd ./src text phpmd.xml
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output